M48
; DRILL file {KiCad 8.0.4} date 2024-12-31T00:11:02+0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-31T00:11:02+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X117.4Y-94.6
X117.4Y-105.6
X151.9Y-86.0
X151.9Y-97.0
T2
X118.4Y-81.0
X118.4Y-117.0
X157.0Y-81.0
X157.0Y-117.0
M30
